### ISSUE TITLE
generate_reads.py script does not generate reverse complement sequences

### ISSUE THREAD

**Issue by fpusan** [sej917/BEAR#14]
When running the generate_reads.py script in paired end mode, the resulting reverse sequences are actually reversed chunks of the template genome, instead of reverse complements. This can be traced to this piece of code.

`read2 = i.seq[end2:start2:-1]`

and can easily be fixed with something along the lines of,

```
comp = {'A':'T', 'T':'A', 'G':'C', 'C':'G'}
read2 = ''.join([comp[b] for b in i.seq[end2:start2:-1]])
```

This issue renders BEAR literally unusable for any project involving paired end reads (Illumina?), and is actually a duplicate of issue https://github.com/sej917/BEAR/issues/1, which you guys marked as closed without apparently having understood what the OP meant.

The OP in https://github.com/sej917/BEAR/issues/12 expressed his surprise at the fact that such blatant errors had made it through testing/peer review, and I can't help but to concur.

**Comment by sej917** [comment]
Hi, thanks for catching this. This issue should be resolved now. Sorry for any inconvenience it caused!

**Comment by fpusan** [comment]
Thanks your prompt response.
Line 109 needs to be cleaned up. As of now it is:
`>>>>>>> bfdb786edfda546c5c19246889bf23c9cc97d690`
Also, the issue has not been fully removed yet. As of now, the fix has been applied to the generation of paired end reads, but not to the generation of single-end reads in reverse orientation.
See lines 118-121
```
				if(args.direction and random.random() < 0.5):
                                        #reverse orientation
					f4.write(">%s\n" % i.description)
                                        f4.write("%s\n" % read[::-1])
```
This is still producing reversed (not reverse-complement) reads.
