### ISSUE TITLE
Non-Unique Read Headers

### ISSUE THREAD

**Issue by Agihawi** [sej917/BEAR#20]
Hello,

I have recently used this tool to simulate 200 mixed human/bacterial metagenomes. I noticed that the final sequence files were given the header names of the contigs that the sequences originated from and not given unique read headers. This caused some issues in assessing the species present using MetaPhlAn2.

See below my performance (measured by pythagorean distance between PPV and sensitivity) before and after applying unique read headers. 

Before:
![image](https://user-images.githubusercontent.com/32674303/39119022-c1af91b2-46e2-11e8-9ec3-a3035c389dc7.png)

After: 
![image](https://user-images.githubusercontent.com/32674303/39118969-a44ddf16-46e2-11e8-8300-f3fad1416b9c.png)

It would be nice if the reads were automatically given unique headers or labelled as part of the creation process.

Kind Regards,
Abe

**Comment by sej917** [comment]
Finally got around to doing this, reads should be unique now.
