### ISSUE TITLE
Support for ambiguous reference nucleotides

### ISSUE THREAD

**Issue by Agihawi** [sej917/BEAR#21]
I have been struggling to generate paired end reads using BEAR and my selection of reference genomes.

After some investigation it was noticed that generate_reads.py was unable to obtain the reverse complement for ambiguous nucleotides. I have amended the comp dictionary on line 49 of generate_reads.py to add support for ambiguous nucleotides and for upper/lower case bases as follows:

`comp = {'A':'T', 'T':'A', 'G':'C', 'C':'G', 'N':'N', 'R':'Y', 'Y':'R', 'K':'M', 'M':'K', 'W':'W', 'S':'S', 'D':'H', 'H':'D', 'B':'V', 'V':'B', 'a':'t', 't':'a', 'g':'c', 'c':'g', 'n':'n', 'r':'y', 'y':'r', 'k':'m', 'm':'k', 'w':'w', 's':'s', 'd':'h', 'h':'d', 'b':'v', 'v':'b'}`

I thought I would share just in case anyone else had issues with this.

Abe

**Comment by sej917** [comment]
Thank you! Closing this as it is now implemented as of 659ba23
