### ISSUE TITLE
Second reads never map

### ISSUE THREAD

**Issue by schmeing** [sej917/BEAR#22]
Second reads never map, because they are only reversed, but not complemented in the current version.

Calling the simulation with:
```
./generate_reads.py -r ref.fa -a abundance.txt -o uniform-reads -t 18000000  -l 100 -i 164 -s 30
./trim_reads.pl -i reads1.fastq -f uniform-reads.1.fasta -o bear1.fq -r dri_read1.txt.per -q reads1.fastq.err.qual -m reads2.fastq.err.matr
./trim_reads.pl -i reads2.fastq -f uniform-reads.2.fasta -o bear2.fq -r dri_read2.txt.per -q reads2.fastq.err.qual -m reads2.fastq.err.matr
```

**Comment by sej917** [comment]
Hi, please use the `-d` flag with generate_reads.py. That should give you the reverse complements. If you're getting paired reads without that option, that's something that needs fixing (please open a separate issue if that's the case!). 

If `-d` doesn't fix this, please let me know!

**Comment by schmeing** [comment]
Using the `-d` flag resulted in 50% mapping rate for the uniform-reads again. This time either the pair maps or it does not, so it is not first read maps, second doesn't anymore. I did not check if I got only reversed, but not complemented reads this time. However, I assume it is the case, which then brings up the question why suddenly both reads of a pair are reversed?

Your second part I did not fully understand. I did get paired reads as I would expect with the options `-i 164 -s 30`. So what other issue do you like to have? That the `-d` is not automatically set, when generating paired reads?

For the recent test I used the recently updated version on github. If it helps I can also provide the ref.fa and abundance.txt for this, but I don't expect it to have anything to do with them.

**Comment by sej917** [comment]
Thanks for your patience, I just pushed a new commit that should take care of this and I can confirm that I was getting both F and R reads to map after generating data with this command:

`./generate_reads.py -r ref.fna -a abundance.txt -o output -l 100 -i 164 -s 30 -t 20000 -d`

I'll close this issue as I think it's solved but feel free to reopen if there's still a problem!
