### ISSUE TITLE
Drisee won't work because of run_find_steiner.pl

### ISSUE THREAD

**Issue by vectorio** [sej917/BEAR#3]
These days I succeeded to install BEAR and DRISEE on my cluster and run it. After a few hours, this is what I get from drisee.py:

---

Traceback (most recent call last):
  File "/user/home/gent/vsc414/vsc41463/DRISEE-master/drisee.py", line 585, in <module>
    sys.exit(main(sys.argv))
  File "/user/home/gent/vsc414/vsc41463/DRISEE-master/drisee.py", line 495, in main
    finish = pool.map(process_bin, to_process,1)
  File "/apps/gent/SL6/sandybridge/software/Python/2.7.6-ictce-5.5.0/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/apps/gent/SL6/sandybridge/software/Python/2.7.6-ictce-5.5.0/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
IOError: run_find_steiner.pl -i /tmp/XrUrFJ6J.drisee/0001031bb47190eea08e30839edd0ad1.fasta -o /tmp/XrUrFJ6J.drisee/0001031bb47190eea08e30839edd0ad1.score -l /tmp/XrUrFJ6J.drisee/0001031bb47190eea08e30839edd0ad1.log -t /tmp/XrUrFJ6J.drisee/0001031bb47190eea08e30839edd0ad1 --max_iter 10 --min_conv 3 -s /user/home/gent/vsc414/vsc41463/Mobio_12735_TCCTGAGCAAGGAGTA_L001_R1_001_HTCNFADXX.filt.fastq.uc
## Can not open file /tmp/XrUrFJ6J.drisee/0001031bb47190eea08e30839edd0ad1/55ae4ab27323.1.results: No such file or directory

Any ideas please ?

**Comment by nickjhathaway** [comment]
I have the same exact issue, has anyone solved this?

**Comment by nickjhathaway** [comment]
After some investigating I found that uclust had run out memory and shut down and so, the *.results files weren't created if this helps anyone.

**Comment by vectorio** [comment]
@nickjhathaway my problem was a simple one: I did not have qiime installed at all. You got a different issue. Hope you will be able to solve it on your own my friend !

**Comment by nickjhathaway** [comment]
@vectorio yes, i simply didn't have enough memory, i was working in a virtual image so i just allocated more memory for the image
